[project]
name = "milieumanager-bot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "instructor>=1.7.2",
    "openai>=1.59.9",
    "pandas>=2.2.3",
    "pydantic>=2.10.5",
    "streamlit>=1.41.1",
]
